site_name: Five Year Plan Analysis
theme:
  name: material
  palette:
    primary: blue
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - table-reader
  
nav:
    - Home: index.md
    - Install: install.md
    - Usage: 
      - Overview: usage/overview.md
      - Working Interactively: usage/interactive.md
      - Annual Updates: usage/updates.md
    - The Code Structure: 
      - Introduction: structure/intro.md
      - The data/ folder: 
        - Overview: structure/data/overview.md
        - Plan Details: structure/data/plan_details.md
      - Analysis Steps:
        - "1. Data Processing": structure/steps/1-processing.md
        - "2. Forecast Prep": structure/steps/2-forecast-prep.md
        - "3. Exploratory Modeling": structure/steps/3-exploratory.md
        - "4. Forecasting": structure/steps/4-forecast.md
          # - Overview: structure/steps/4-forecast/overview.md
          # - Steps: structure/steps/4-forecast/steps.md
          # - Bestfit: structure/steps/4-forecast/bestfit.md
          # - Results: structure/steps/4-forecast/results.md


    